### ISSUE TITLE
all-apps page not displayed correctly

### ISSUE THREAD

**Issue by junghans** [exascaleproject/proxy-apps#19]
See XSBench at bottom (cannot scroll more):
<img width="1411" alt="screen shot 2017-08-08 at 15 30 02" src="https://user-images.githubusercontent.com/439483/29095583-88c61876-7c4e-11e7-8d14-6731f01202fe.png">

**Comment by bhatele** [comment]
Hi Christoph, we are aware of the problem and looking into it.

**Comment by nikhil-jain** [comment]
I changed the placement to be relative instead of absolute. Let me know this look well.
