### ISSUE TITLE
MCB not showing up in application list

### ISSUE THREAD

**Issue by homerdin** [exascaleproject/proxy-apps#31]
The MCB application is not showing up on the webpage for me.  Both mcb.md and mcb.json seem correct in the repository.

**Comment by nikhil-jain** [comment]
I dont think that mcb.json is correct. It has extra quotes around the app name ("Monte Carlo Benchmark") which would confuse a json reader.

**Comment by nikhil-jain** [comment]
Resolved in 9f4f03f1e619bc8e56fa5c22aaf30804d1975c1d
